FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    texlive \
    texlive-latex-extra \
    imagemagick

RUN mkdir /app/tmp

WORKDIR /app

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt
RUN sed -i '/<policy domain="coder" rights="none" pattern="PDF" \/>/d' /etc/ImageMagick-6/policy.xml
COPY . /app
CMD ["python3", "app.py"]
